export const TEMPLATE_LIST_REQUEST = "TEMPLATE_LIST_REQUEST"
export const TEMPLATE_LIST_SUCCESS = "TEMPLATE_LIST_SUCCESS"
export const TEMPLATE_LIST_FAIL = "TEMPLATE_LIST_FAIL"

export const TEMPLATE_DETAILS_REQUEST = "TEMPLATE_DETAILS_REQUEST"
export const TEMPLATE_DETAILS_SUCCESS = "TEMPLATE_DETAILS_SUCCESS"
export const TEMPLATE_DETAILS_FAIL = "TEMPLATE_DETAILS_FAIL"

export const CREATE_TEMPLATE_REQUEST = "CREATE_TEMPLATE_REQUEST"
export const CREATE_TEMPLATE_SUCCESS = "CREATE_TEMPLATE_SUCCESS"
export const CREATE_TEMPLATE_FAIL = "CREATE_TEMPLATE_FAIL"
export const CREATE_TEMPLATE_RESET = "CREATE_TEMPLATE_RESET"

export const MY_TEMPLATE_REQUEST = "MY_TEMPLATE_REQUEST"
export const MY_TEMPLATE_SUCCESS = "MY_TEMPLATE_SUCCESS"
export const MY_TEMPLATE_FAIL = "MY_TEMPLATE_FAIL"
export const MY_TEMPLATE_RESET = "MY_TEMPLATE_RESET"

export const UPDATE_TEMPLATE_REQUEST = "UPDATE_TEMPLATE_REQUEST"
export const UPDATE_TEMPLATE_SUCCESS = "UPDATE_TEMPLATE_SUCCESS"
export const UPDATE_TEMPLATE_FAIL = "UPDATE_TEMPLATE_FAIL"
export const UPDATE_TEMPLATE_RESET = "UPDATE_TEMPLATE_RESET"


export const DELETE_TEMPLATE_REQUEST = "DELETE_TEMPLATE_REQUEST"
export const DELETE_TEMPLATE_SUCCESS = "DELETE_TEMPLATE_SUCCESS"
export const DELETE_TEMPLATE_FAIL = " DELETE_TEMPLATE_FAIL"


export const TEMPLATE_PURCHASE_REQUEST = "TEMPLATE_PURCHASE_REQUEST"
export const TEMPLATE_PURCHASE_SUCCESS = "TEMPLATE_PURCHASE_SUCCESS"
export const TEMPLATE_PURCHASE_FAIL = " TEMPLATE_PURCHASE_FAIL"
export const TEMPLATE_PURCHASE_RESET = " TEMPLATE_PURCHASE_RESET"


export const PAY_TEMPLATE_REQUEST = "PAY_TEMPLATE_REQUEST"
export const PAY_TEMPLATE_SUCCESS = "PAY_TEMPLATE_SUCCESS"
export const PAY_TEMPLATE_FAIL = "PAY_TEMPLATE_FAIL"
export const PAY_TEMPLATE_RESET = "PAY_TEMPLATE_RESET"


export const PAID_TEMPLATE_REQUEST = "PAID_TEMPLATE_REQUEST"
export const PAID_TEMPLATE_SUCCESS = "PAID_TEMPLATE_SUCCESS"
export const PAID_TEMPLATE_FAIL = "PAID_TEMPLATE_FAIL"
export const PAID_TEMPLATE_RESET = "PAID_TEMPLATE_RESET"



export const REVIEW_TEMPLATE_REQUEST = "REVIEW_TEMPLATE_REQUEST"
export const REVIEW_TEMPLATE_SUCCESS = "REVIEW_TEMPLATE_SUCCESS"
export const REVIEW_TEMPLATE_FAIL = "REVIEW_TEMPLATE_FAIL"
export const REVIEW_TEMPLATE_RESET = "REVIEW_TEMPLATE_RESET"


export const DOWNLOAD_TEMPLATE_REQUEST = "DOWNLOAD_TEMPLATE_REQUEST"
export const DOWNLOAD_TEMPLATE_SUCCESS = "DOWNLOAD_TEMPLATE_SUCCESS"
export const DOWNLOAD_TEMPLATE_FAIL = "DOWNLOAD_TEMPLATE_FAIL"
export const DOWNLOAD_TEMPLATE_RESET = "DOWNLOAD_TEMPLATE_RESET"
